### ISSUE TITLE
Default trainer from Gluon package in the deep_learning_experiments script

### ISSUE THREAD

**Issue by BoudabousSafa** [rakshitha123/TSForecasting#10]
Hello, thank you for making this benchmark available.
I noticed that the deep learning implementation relies on the Gluon package and in the train_model function, the trainer is always used with the defaulted parameters. I wonder if it is not better to adjust some params to the considered dataset (basically the num_batches_per_epoch parameter).

**Comment by rakshitha123** [comment]
Hello,

Yes, the performance of the models can be improved by tuning their hyperparameters with each dataset. But in our work, we executed all models as benchmarks and thus, we executed all of them with their default parameters. We have mentioned that in our [paper ](https://openreview.net/pdf?id=wEc1mgAjU-) as well.

**Comment by BoudabousSafa** [comment]
Thanks @rakshitha123 for your response.
