### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aldro61** [rakshitha123/TSForecasting#3]
Hi,

Thanks for making this data repository available! Could you please add a license for the code (e.g., the data loader)?

From [GitHub docs](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository):
> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

Thank you,
Alex

**Comment by rakshitha123** [comment]
Hi,
Thanks, our code is licensed under a Creative Commons Attribution 4.0 International License. The details were added to https://github.com/rakshitha123/TSForecasting/blob/master/LICENSE.md
