### ISSUE TITLE
Missing documentation in the notebook

### ISSUE THREAD

**Issue by hkayabilisim** [rakshitha123/TSForecasting#5]
In the forecastingdata_python notebook, it should be nice if you could add something like this: 

After a fresh R installation, you need to install devtools by running "install.packages("devtools")" in R command line.

By the way, thank you for this great forecasting repository and the tools you created in the GitHub repo.

**Comment by hkayabilisim** [comment]
Update: you can also include "install.packages('tidyverse')" to the requirements in the notebook.

**Comment by rakshitha123** [comment]
Hi,

Thanks a lot for the encouraging comments. It is great to hear that you found our repository useful.

Thanks for the package suggestions as well. I have now included the installation statements of "devtools" and "tidyverse" packages in the "forecastingdata_python" notebook.
