### ISSUE TITLE
sktime integration of `data_loader.convert_tsf_to_dataframe`

### ISSUE THREAD

**Issue by fkiraly** [rakshitha123/TSForecasting#7]
Really nice collection of forecasting benchmark datasets you have here!

We were wondering (at `sktime`) whether you would be open for us to integrate (a possibly modified) `data_loader.convert_tsf_to_dataframe` into the `data_io` module of `sktime`, using the Monash forecasting repository as a data endpoint. Of course with proper attribution and crediting of the source.

Since `tsf` is based on the `ts` format and the loaders are similar, it would fit nicely with a current refactoring effort in the space.

If you'd be up for a chat and/or collaboration, feel free to visit us on the `sktime` slack, `forecasting` or `forecasting-global` channel.
(go https://github.com/alan-turing-institute/sktime, README -> slack badge at the top)
Might also be nice to collaborate on "nice" benchmark functionality, which can be loaded as a package and which directly interfaces with existing base class templates (with no need to write extra glue code that's special to the benchmark)

**Comment by fkiraly** [comment]
(I assume the code is mainly yours, @rakshitha123?)

**Comment by fkiraly** [comment]
FYI `sktime` collaborators, @ltsaprounis, @danbartl, @aiwalter, @satya-pattnaik

**Comment by rakshitha123** [comment]
Hi,

Many thanks for reaching us. Yes, the implementations in this repository were mainly done by me and @pmontman.

We are happy to integrate the .tsf loading functionality into sktime. If it is fine, can you please let us know how we should proceed with that?

**Comment by fkiraly** [comment]
apologies for the late answer, this is due to Christmas holidays and me checking email less thoroughly.

I'd propose is a call in the new year.
@tonybagnall is currently refactoring the current data input/output module, so might be best to spend 1h of technical meeting to align on target interfaces once people are back from holiday. ts is very similar to tsf, so it's best to try being consistent?

Before that, I suggest you join the sktime slack and ping @tonybagnall in the contributors channel, we can have an asynchronous pre-discussion and some introductions there.

**Comment by rakshitha123** [comment]
Many thanks, @fkiraly. Sounds great!
