### ISSUE TITLE
covariate and forecasting target

### ISSUE THREAD

**Issue by kashif** [rakshitha123/TSForecasting#9]
Hello! I had a question regarding the forecasting target vs. additional covariates in the dataset. For example, in the `temperature_rain` dataset there are some fields that I assume are the forecast target from the names of the column while others are covariates... How does the `tst` format distinguish between those?

**Comment by rakshitha123** [comment]
For our current benchmarking model implementations in this repo, we have considered all series as target series, not covariates. 

However, you can use the name of the series (series_name attribute) to distinguish between target series and covariate series. Within benchmarking functions, then you can input the series into models as targets and covariates separetly. Although our .tsf format supports the inclusion of covariate series, the models in our repo do not have this implementation as our focus was to run the benchmarks in their most simple format without covariates.

**Comment by kashif** [comment]
right, so my question was how does the `tsf` format supports covariates? will the `series_name` have an `fcst_` at the start to distinguish it as a target? For example in the `temperature_rain` dataset the  `series_name` is just a unique name for each time series... while the `obs_or_fcst` column has fields with names that seem to encode if they are forecast target or covariate... although I am not sure about that either...

**Comment by rakshitha123** [comment]
Sure, you can use a prefix with a series_name to identify whether it is a covariate series. We have done something similar in one of our latest project available at https://github.com/rakshitha123/SETAR_Trees. If you see a dataset with covariates in the "datasets" folder (e.g. Rossmann with covariates), you'll find covariate series in their starting with prefix such as "Customers", "Open" and "Promo" where the target series start with the prefix "T".

**Comment by kashif** [comment]
thanks @rakshitha123 I'll have a look, I don't have my own data but wish to use your repository for my models... the dataset convention I have is a bit more verbose in defining the covariates as well as categorical features explicitly and I am trying to convert from the tsf format to my convention...
